### PR TITLE
MLW 1200 Add IC3D column in appointment report

### PR DESCRIPTION
**Pull request by kmatiya**
@cioan 

For your review on the issue of print ic3d_number in excel

### CODE REVIEW

**Comment by cioan** [comment]
Hi @kmatiya , I think I got it working by adding the ic3d_number to the report similar to the ccc number. Please let me know what you think. Thanks!

**Comment by kmatiya** [comment]
@mseaton Could you support to merge the PR with @cioan away.

**Comment by mseaton** [comment]
Hi @kmatiya - looks good to me.  I've invited you to join the Github group that will give you write access to this repository, so you can more easily move at your own pace and you and @tlimbani can code review each other's work and merge without waiting on our Boston team.  Still obviously happy and interested to stay connected and review PRs, but don't want to be a bottleneck to you, especially since many of us will be offline a lot this summer.

Regarding this PR, it looks good to me, though it looks to be broader in scope (has changes related to location tags for medic mobile), so you may want to double check that it covers the ground you intend.

**Comment by kmatiya** [comment]
Thanks @mseaton  for the github group invite. 

You can also provide access to the https://github.com/PIH/pih-pentaho repository for updating the Malawi warehouse tables. We have a number of tickets related to the warehouse we working on.

**Comment by mseaton** [comment]
Good idea @kmatiya  - I've done that.

**Pull request merged**
