### PR TITLE
MLW-707, modifications to answer labels, and adding field for weight change

### PR DESCRIPTION
**Pull request by tlimbani**
Clinical team tested out the mastercard on Bwenzi and after feedback made changes/modifications below:

- Added  field for **weight change**

- Renamed some answer labels to increase/decrease as per clinical preference

### CODE REVIEW

**Comment by cioan** [comment]
Thanks @tlimbani ! This looks good. I will deploy those changes to the bwenzi server too.

**Comment by tlimbani** [comment]
Thanks @cioan! 

But I made a mistake on the prior commit. Used a wrong UUID for weight change so testing it on Bwenzi the visits could not load in the flowsheet.  
Corrected that and now it's working fine.

**Comment by cioan** [comment]
No worries @tlimbani . I will merge the latest changes now.

**Comment by tlimbani** [comment]
Alright thank you @cioan!

**Pull request merged**
