### PR TITLE
MLW-707, CHF mastercard modifications

### PR DESCRIPTION
**Pull request by tlimbani**
- Added CHF forms to the list of forms to be initialized

- Added CHF metadata to the patient dashboard

- Added new concept answer and set member to old coded and convSet concept, respectively

- Added UUIDs for concepts used in the forms / old and new concepts, except "8612 - Bisoprolol" which is an existing concept, because when I use a UUID I get an Illegal Argument Exception. 
Will add a UUID as well once I figure it out. 

But otherwise everything seem to be working. 

Let me know when you try it out if you see anything that needs some work.

### CODE REVIEW

**Comment by cioan** [comment]
It looks great @tlimbani ! I am going to merge those changes and then test them on my machine. Thanks!

**Comment by tlimbani** [comment]
Thank you so much @cioan!

**Comment by cioan** [comment]
Nice job @tlimbani ! I have deployed the latest pihmalawi code that includes the CHF mastercard to the bwenzi server. Thanks!

**Comment by tlimbani** [comment]
Thank you @cioan! Just waiting for feedback from Alex and the clinical team to test it out. I let them know that it's now available on Bwenzi.

**Pull request merged**
